apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: aha04266-app-pipeline
spec:
  workspaces:
    - name: aha04266-app-pipeline-shared-data
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/aha04266_ibm/stt-app
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/AHA04266/speech-to-text-code-pattern.git
        - name: revision
          value: checkride 
        - name: sslVerify
          value: "false"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: aha04266-app-pipeline-shared-data
    - name: install-dependencies
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: aha04266-app-pipeline-shared-data
      params:
        - name: ARGS
          value:
            - clean-install
      runAfter:
        - clone-repository
    - name: build-image
      runAfter:
        - install-dependencies
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: aha04266-app-pipeline-shared-data
    - name: kustomize-build
      runAfter:
        - build-image
      params:
        - name: image-with-tag
          value: "quay.io/aha04266_ibm/stt-app=$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: aha04266-app-pipeline-shared-data
    - name: deploy
      runAfter:
        - kustomize-build
      params:
        - name: app-namespace
          value: aha04266-app
        - name: app-name
          value: aha04266-stt-app
      taskRef:
        kind: Task
        name: deploy
      workspaces:
        - name: source
          workspace: aha04266-app-pipeline-shared-data
#    - name: gitops
#      runAfter:
#        - deploy
#      taskRef:
#        kind: Task
#        name: gitops
#      params:
#        - name: app-name
#          value: aha04266-stt-app
#        - name: sha
#          value: "$(tasks.clone-repository.results.commit)"
#      workspaces:
#        - name: source
#          workspace: aha04266-app-pipeline-shared-data